sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X0OHfFC6XJpMc3rMNQveChl07xbBg2vObB75mtkpb3KbnhWnwpm4VLgaVMz9/iKRGpC3QwxCr9M5xRxm+B16KSDJNofKkWfXtEFiK5Wc9okYmmG+GL+jhrgzaCIXGBjRvxihMi58lDtzo9pYjAbMJPYJQSdlte1/BgUcGwpDrAxQsK/79G4L6djr8lzah/+dJqrpAwUFa9muWYgyFyxwDJRUAB8D9KPNnqVRRpAEuEX51jUJ/3O1TfkQiUarh2QIyuiWkJtI9ioni8eg1TRpGSukf2mF+86BsdKqyqXtf+T0eXpgcTzEprFkIKmzKJ5Nn57TLDuMV+Opnigs3kg1tjOA74nJ6XDnc0AutK8yN0lTtGasT6tXytiddeb+WYVAPk5rok/58eib0Wt/JjGXKq14LbavAa1BLah9eGgr4jYNupYcFxhFAmBKkOsJ+n2aYWcg/YGl3wkTz+aMEGYaZiv2l5l3HT/r09xPfEbMyxOwO7wcNj3a4W/OMHvmw1swWEU8j8iP2TjQbAVkXzxFnBW2G/CFk1t+L26Uxq51KV6YoOd5a/hTjuqb951ZNgzbJ2hx6EPIUiicgUvGs7dyeT3QD+KyDL2/kenAEO+7aHH10TV91oHe5E3bJNsGVf5ZVs6kd3mBVpHK/aBH7AKC5XFh5hXQqn7Ae3kLrXV81r8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Iceberg-Express_2325
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy